# Generated by Django 6.0 on 2025-12-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Молоток', 'Молоток'), ('Викрутка', 'Викрутка'), ('Дриль', 'Дриль')], max_length=50)),
                ('tool_type', models.CharField(max_length=50)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
